# Generated by Django 2.2.8 on 2020-10-24 00:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dailyRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to=myapp.models.get_image_path)),
                ('descripcion', models.TextField(max_length=500)),
                ('pax', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reservaciones',
                'ordering': ('total', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('iconClass', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='RentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField(blank=True, null=True)),
                ('dateTo', models.DateField(blank=True, null=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Estate')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.Reservation')),
            ],
            options={
                'verbose_name_plural': 'Fechas de Alquiler',
                'ordering': ('dateFrom', 'dateTo', 'estate'),
            },
        ),
        migrations.AddField(
            model_name='estate',
            name='services',
            field=models.ManyToManyField(to='myapp.Service'),
        ),
    ]
